[build]
  publish = "docs"
  command = "hugo --gc --minify --buildFuture -d docs"

[build.environment]
  HUGO_VERSION = "0.140.0"
  HUGO_EXTENDED = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -d docs"

[context.branch-deploy]
  command = "hugo --gc --minify -d docs"

[[redirects]]
  from = "/*"
  to = "https://corerocket.net/:splat"
  status = 301
  force = true